name: dolfinx-dev
dependencies:
  - python
  - numpy
  - pybind11
  - cmake
  - cxx-compiler
  - pkg-config
  - cffi
  - boost-cpp
  - parmetis
  - ptscotch
  - pugixml
  - mpich
  # - petsc=*=complex*
  - petsc
  - slepc
  - libadios2=*=mpi*
  - openblas
  - hdf5=1.12
  - petsc4py
  - mpi4py
  - git
  - fenics-ufl
  - matplotlib
  - gmsh
  - python-gmsh
  - scipy
  - pyvista
